// <auto-generated />
using System;
using AirplaneRegister.WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirplaneRegister.WebAPI.Migrations
{
    [DbContext(typeof(AirplaneRegisterContext))]
    partial class AirplaneRegisterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AirplaneRegister.WebAPI.Models.AirplaneRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirplaneTypeId");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneTypeId");

                    b.ToTable("AirplaneRegisters");
                });

            modelBuilder.Entity("AirplaneRegister.WebAPI.Models.AirplaneTypes", b =>
                {
                    b.Property<int>("AirplaneTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirplaneTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("AirplaneTypeId");

                    b.ToTable("AirplaneTypes");
                });

            modelBuilder.Entity("AirplaneRegister.WebAPI.Models.AirplaneRegister", b =>
                {
                    b.HasOne("AirplaneRegister.WebAPI.Models.AirplaneTypes", "AirplaneType")
                        .WithMany()
                        .HasForeignKey("AirplaneTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
